In [1]:
import h5py
import kedro_datasets
from kedro.io import data_catalog
import pandas as pd
import os
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('../data/01_raw/drugs_dataset/all_drugs_dataset.csv')

In [10]:
df.sort_values('CID', inplace=True)
display(df[df['CID'] == 137183587])
df.tail()


CID  HBondAcceptorCount  HBondDonorCount   
9608  137183587                10.0              5.0  \

                                         IsomericSMILES  MolecularWeight   
9608  C1[C@@H](N(C2=C(N1)N=C(NC2=O)N)C=O)CNC3=CC=C(C...            511.5  \

      LogP  RuleFive MATC_Code_Short MATC_Code_Explanation  
9608   NaN       0.0               V               Various

CID  HBondAcceptorCount  HBondDonorCount   
9781  171040046                16.0             13.0  \
9782  171342013                19.0              9.0   
9783  171369730                19.0              6.0   
9784  171378396                14.0              3.0   
9785  172400020                 1.0              1.0   

                                         IsomericSMILES  MolecularWeight   
9781  C1C[C@H](N(C1)C(=O)[C@@H]2CSSC[C@@H](C(=O)N[C@...           1042.2  \
9782  C1=CC(=C(C=C1CCC(=O)NCCCCCC(=O)NCCCC[C@@H](C(=...           1029.9   
9783  CCC1C(=O)N2CCCC2C(=O)N(C(C(=O)N3CCC(=O)CC3C(=O...           1349.5   
9784  CC[C@H](C)[C@@H]1[C@H](CC[C@@]2(O1)C[C@@H]3C[C...            875.1   
9785  C[C@H]\1CC[C@@H](C/C1=C/C=C/2\CCC[C@@]3([C@H]2...            398.7   

      LogP  RuleFive MATC_Code_Short   
9781  -4.2       0.0               H  \
9782   NaN       0.0               V   
9783   NaN       0.0               J   
9784   4.1       0.0               P   
9785   7.7       1.0               A   

                                  MATC_Code_Explanation  
9781  Systemic hormonal preparations excluding sex h...  
9782                                            Various  
9783                    Antiinfectives for systemic use  
9784  Antiparasitic products insecticides and repell...  
9785                    Alimentary tract and metabolism

In [39]:
for file in os.listdir(os.path.join('..','data','05_model_input','featurized_data')):
    df = pd.read_parquet(os.path.join('..','data','05_model_input','featurized_data', file))
    print(file, df.columns[6])

Balanced_000000001_000010000 FP
Balanced_000000001_000010000_fixed FP
Balanced_000010001_000020000 FP
Balanced_000020001_000030000 FP
Balanced_000030001_000040000 FP
Balanced_000040001_000050000 FP
Balanced_000050001_000060000 FP
Balanced_000060001_000070000 FP
Balanced_000070001_000080000 FP
Balanced_000080001_000090000 FP
Balanced_000090001_000100000 FP
Balanced_000100001_000110000 FP
Balanced_000110001_000120000 FP
Balanced_000120001_000130000 FP
Balanced_000130001_000140000 FP
Balanced_000140001_000150000 FP
Balanced_000150001_000160000 FP
Balanced_000160001_000170000 FP
Balanced_000170001_000180000 FP
Balanced_000180001_000190000 FP
Balanced_000190001_000200000 FP
Balanced_000200001_000210000 FP
Balanced_000210001_000220000 FP
Balanced_000220001_000230000 FP
Balanced_000230001_000240000 FP
Balanced_000240001_000250000 FP
Balanced_000250001_000260000 FP
Balanced_000260001_000270000 FP
Balanced_000270001_000280000 FP
Balanced_000280001_000290000 FP
Balanced_000290001_000300000 FP
Ba

In [35]:
for file in os.listdir(os.path.join('..','data','05_model_input','featurized_data')):
    df = pd.read_parquet(os.path.join('..','data','05_model_input','featurized_data', file))
    print(df.columns)
    df.columns = df.columns.str.replace('Morgan2FP', 'FP')
    print(df.columns)
    df.to_parquet(os.path.join('..','data','05_model_input','featurized_data', file))

Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'Morgan2FP'],
      dtype='object')
Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'FP'],
      dtype='object')
Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'FP'],
      dtype='object')
Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'FP'],
      dtype='object')
Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'Morgan2FP'],
      dtype='object')
Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'FP'],
      dtype='object')
Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'Morgan2FP'],
      dtype='object')
Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Accepto

In [28]:
df = pd.read_parquet(os.path.join('..','data','05_model_input','featurized_data', 'Balanced_000000001_000010000'))
df.head()

SMILES  Molecular Weight   
0  CC(O)CN(CC(C)O)c1nc(Nc2ccc(S(=O)(=O)[O-])cc2)n...          1221.164  \
1  Cl[Rh](Cl)Cl.c1ccc(P(CC[As](c2ccccc2)c2ccccc2)...           831.721   
2                           CCCCCCCCCCCCN1CNC(=O)NC1           269.433   
3  Cl[Sn](Cl)(Cc1ccccc1)Cc1ccccc1.[O-][n+]1cccc2c...           568.092   
4   Cc1nccn1-c1ccc(Cl)cc1/N=C/c1ccc(N(CCCl)CCCl)cc1F           453.776   

   H-Bond Donors  H-Bond Acceptors      LogP  RuleFive   
0              8                28 -10.03020         0  \
1              0                 0   7.47820         0   
2              2                 2   3.43710         1   
3              0                 2   6.49140         0   
4              0                 4   6.00782         1   

                                           Morgan2FP  
0  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [29]:
df.columns = df.columns.str.replace('Morgan2FP', 'FP')

In [30]:
df.columns

Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'FP'],
      dtype='object')

In [31]:
df.to_parquet(os.path.join('..','data','05_model_input','featurized_data', 'Balanced_000000001_000010000_fixed'))

In [32]:
df = pd.read_parquet(os.path.join('..','data','05_model_input','featurized_data', 'Balanced_000000001_000010000_fixed'))

In [33]:
df.head()

SMILES  Molecular Weight   
0  CC(O)CN(CC(C)O)c1nc(Nc2ccc(S(=O)(=O)[O-])cc2)n...          1221.164  \
1  Cl[Rh](Cl)Cl.c1ccc(P(CC[As](c2ccccc2)c2ccccc2)...           831.721   
2                           CCCCCCCCCCCCN1CNC(=O)NC1           269.433   
3  Cl[Sn](Cl)(Cc1ccccc1)Cc1ccccc1.[O-][n+]1cccc2c...           568.092   
4   Cc1nccn1-c1ccc(Cl)cc1/N=C/c1ccc(N(CCCl)CCCl)cc1F           453.776   

   H-Bond Donors  H-Bond Acceptors      LogP  RuleFive   
0              8                28 -10.03020         0  \
1              0                 0   7.47820         0   
2              2                 2   3.43710         1   
3              0                 2   6.49140         0   
4              0                 4   6.00782         1   

                                                  FP  
0  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [38]:
df.columns[6]

'FP'

In [4]:
df.head()

SMILES  Molecular Weight   
0  COC1=C2CC(C)CC(OC)[C@@H](OC(=O)CCN)[C@H](C)C=C...           631.723  \
1  COC(=O)C1(C)CCC2(C(=O)O)CCC3(C)C(=CCC4C5(C)CC(...           826.974   
2  Nc1ncnc2c1ncn2C1OC(COP(=O)(O)OC2C(O)C(COP(=O)(...           925.663   
3                            CCC(CC(C)C)C(=O)OCC(C)C           200.322   
4  O=S(O)c1cc(Cl)ccc1-c1ccc(Cl)c(SSSc2cc(-c3ccc(C...           668.519   

   H-Bond Donors  H-Bond Acceptors     LogP  RuleFive   
0              3                11   2.3081         0  \
1              9                15   0.6174         0   
2             10                29  -3.6148         0   
3              0                 2   3.2579         1   
4              2                 5  10.2430         0   

                                           Morgan2FP  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

Split csv in 2

In [68]:
df = pd.read_csv(os.path.join('..','data','01_raw','csv_files', 'Balanced_000080001_000090000.csv'))

In [69]:
df['RuleFive'].value_counts()


RuleFive
0    2191
1    2113
Name: count, dtype: int64

In [7]:
df_to_split = pd.read_csv('../data/01_raw/Compound_000000001_000500000.csv')

In [9]:
df1 = df_to_split.iloc[:1000]
df2 = df_to_split.iloc[1000:2000]

In [14]:
df1.to_csv('../data/01_raw/Compound_000000001_000000999.csv', index=False)
df1.to_csv('../data/01_raw/Compound_000001000_000001999.csv', index=False)

In [81]:
df = pd.read_parquet('../data/05_model_input/featurized_data/Compound_000000001_000500000')

In [93]:
df_10=df.iloc[:10000]
df_10_20=df.iloc[10000:20000]
df_20_30=df.iloc[20000:30000]
df_30_40=df.iloc[30000:40000]


In [94]:
df_10.to_parquet('../data/05_model_input/featurized_data/Compound_000000001_000010000')
df_10_20.to_parquet('../data/05_model_input/featurized_data/Compound_000010000_000020000')
df_20_30.to_parquet('../data/05_model_input/featurized_data/Compound_000020000_000030000')
df_30_40.to_parquet('../data/05_model_input/featurized_data/Compound_000030000_000040000')

In [84]:
df_10

SMILES  Molecular Weight   
0                      CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C           203.238  \
1                         CC(=O)OC(CC(=O)O)C[N+](C)(C)C           204.246   
2                                  O=C(O)C1=CC=CC(O)C1O           156.137   
3                                               CC(O)CN            75.111   
4                                    NCC(=O)COP(=O)(O)O           169.073   
...                                                 ...               ...   
9995                                 CCOC(O)C(Cl)(Cl)Cl           193.457   
9996                                CCOC(=O)C(Cl)(Cl)Cl           191.441   
9997                          O=C([O-])C(=O)[O-].[Fe+2]           143.863   
9998         CC12CC(O)C3C(CCC4CC(O)CCC43C)C1CCC2C(=O)CO           350.499   
9999  CC(CCC(=O)NCCS(=O)(=O)O)[C@H]1CC[C@H]2[C@@H]3[...           499.714   

      H-Bond Donors  H-Bond Acceptors    LogP  RuleFive   
0                 0                 4 -1.2357         1  \
1                 1                 3  0.0990         1   
2                 3                 3 -0.7110         1   
3                 2                 2 -0.6741         1   
4                 3                 4 -1.3765         1   
...             ...               ...     ...       ...   
9995              1                 2  1.7115         1   
9996              0                 2  1.9197         1   
9997              0                 4 -3.5163         1   
9998              3                 4  2.5384         1   
9999              4                 5  3.3973         1   

                                              Morgan2FP  
0     [False, True, False, False, False, False, Fals...  
1     [False, True, False, False, False, False, Fals...  
2     [False, False, False, False, False, False, Fal...  
3     [False, True, False, False, False, False, Fals...  
4     [False, False, False, False, False, False, Fal...  
...                                                 ...  
9995  [False, True, False, False, False, False, Fals...  
9996  [False, False, False, False, False, False, Fal...  
9997  [False, False, False, False, False, False, Fal...  
9998  [False, False, False, False, False, False, Fal...  
9999  [False, True, False, False, False, False, Fals...  

[10000 rows x 7 columns]

In [86]:
df_10_20

SMILES  Molecular Weight   
10000  CC12CCC(=O)CC1CCC1C2C(O)CC2(C)C1CC[C@]2(O)C(=O)CO           364.482  \
10001      CC12CCC(O)CC1CCC1C2CCC2(C)C1CC[C@]2(O)C(=O)CO           350.499   
10002  CC(CCC(=O)NCCS(=O)(=O)O)[C@H]1CC[C@H]2[C@@H]3C...           499.714   
10003  CC(CCC(=O)NCCS(=O)(=O)O)[C@H]1CC[C@H]2[C@@H]3C...           483.715   
10004           CC12CCC3c4ccc(O)cc4CC[C@@H]3C1CC[C@@H]2O           272.388   
...                                                  ...               ...   
19995                CN(C)CCOc1c2c(nc3ccc(Cl)cc13)CCCCC2           318.848   
19996  CC(C[NH+](C)C)Oc1c2c([nH+]c3cc(Cl)ccc13)CCCCC2...           405.797   
19997             CC(CN(C)C)Oc1c2c(nc3cc(Cl)ccc13)CCCCC2           332.875   
19998  CCC12C=CCN3CCC4(c5c(C(=O)OC)cccc5N(C)C4C(O)C1O...           426.513   
19999                       CCOC(=O)C(C#N)=C(C1CC1)C1CC1           205.257   

       H-Bond Donors  H-Bond Acceptors     LogP  RuleFive   
10000              3                 5  1.86150         1  \
10001              3                 4  2.68250         1   
10002              4                 5  3.39730         1   
10003              3                 4  4.42650         1   
10004              2                 2  3.60920         1   
...              ...               ...      ...       ...   
19995              0                 3  4.09750         1   
19996              1                 1 -3.50400         1   
19997              0                 3  4.48600         1   
19998              1                 7  1.87610         1   
19999              0                 3  2.18968         1   

                                               Morgan2FP  
10000  [False, False, False, False, False, False, Fal...  
10001  [False, False, False, False, False, False, Fal...  
10002  [False, True, False, False, False, False, Fals...  
10003  [False, True, False, False, False, False, Fals...  
10004  [False, False, False, False, False, False, Fal...  
...                                                  ...  
19995  [False, False, True, False, False, False, Fals...  
19996  [False, True, True, False, False, False, False...  
19997  [False, True, True, False, False, False, False...  
19998  [False, False, False, False, False, False, Fal...  
19999  [False, False, False, False, False, False, Fal...  

[10000 rows x 7 columns]

In [9]:
type(df.iloc[0]['Morgan2FP'])

numpy.ndarray

In [3]:
dir(kedro_datasets)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__']

In [ ]:
data_catalog.

TypeError: 'module' object is not iterable

In [7]:
model_input = pd.read_csv('../data/05_model_input/model_input.csv')
model_input_val = pd.read_csv('../data/05_model_input/model_input_val.csv')
combined_df_w_fp = pd.concat([model_input, model_input_val], ignore_index=True)

In [8]:
model_input.tail()

SMILES  Molecular Weight   
1324891   CC(=O)COc1c(C(=O)Nc2ccc(C)cc2)nnn1-c1ccc(C)cc1           364.405  \
1324892  O=C(COc1c(C(=O)Nc2ccccc2)nnn1-c1ccccc1)c1ccccc1           398.422   
1324893         C(=Nc1nnc(N2CCC(c3ccccc3)CC2)s1)N1CCOCC1           357.483   
1324894     C[C@@H]1CN(c2nnc(N=CN3CCOCC3)s2)C[C@@H](C)O1           311.411   
1324895       Clc1cccc(N2CCN(c3nnc(N=CN4CCCCC4)s3)CC2)c1           390.944   

         H-Bond Donors  H-Bond Acceptors     LogP          Morgan2FP  RuleFive  
1324891              1                 6  3.10424  [0 0 0 ... 0 0 0]         1  
1324892              1                 6  3.78130  [0 0 0 ... 0 0 0]         1  
1324893              0                 6  2.91410  [0 0 0 ... 0 0 0]         1  
1324894              0                 7  1.14370  [0 0 0 ... 0 0 0]         1  
1324895              0                 6  3.66380  [0 0 1 ... 0 0 0]         1

In [13]:
combined_df_w_fp.to_csv('../data/05_model_input/presplit_model_input.csv', index=False)

In [14]:
len(combined_df_w_fp)

1351934

In [2]:
pick = pd.read_pickle('drugpredictor2/data/05_model_input/input_table.pickle')

In [4]:
pick_val = pd.read_pickle('drugpredictor2/data/05_model_input/input_table_val.pickle')

In [11]:
val_dataset_mock = pd.read_pickle('drugpredictor2/data/05_model_input/input_table_val_mock.pickle')

In [4]:
mock_dataset = pd.read_pickle('../data/05_model_input/input_table_mock.pickle')

In [5]:
mock_dataset

SMILES  Molecular Weight   
1                            CC(=O)OC(CC(=O)O)C[N+](C)(C)C           204.246  \
2                                     O=C(O)C1=CC=CC(O)C1O           156.137   
4                                       NCC(=O)COP(=O)(O)O           169.073   
5                   O=[N+]([O-])c1ccc(Cl)c([N+](=O)[O-])c1           202.553   
6                                       CCn1cnc2c(N)ncnc21           163.184   
...                                                    ...               ...   
1351927        CCOc1c(C(=O)Nc2ccc(OC)cc2)nnn1-c1ccc(OC)cc1           368.393   
1351928  COc1ccc(NC(=O)c2nnn(-c3ccc(OC)cc3)c2OCC(=O)c2c...           488.500   
1351930    O=C(COc1c(C(=O)Nc2ccccc2)nnn1-c1ccccc1)c1ccccc1           398.422   
1351931           C(=Nc1nnc(N2CCC(c3ccccc3)CC2)s1)N1CCOCC1           357.483   
1351932       C[C@@H]1CN(c2nnc(N=CN3CCOCC3)s2)C[C@@H](C)O1           311.411   

         H-Bond Donors  H-Bond Acceptors    LogP  RuleFive   
1                    1                 3  0.0990         1  \
2                    3                 3 -0.7110         1   
4                    3                 4 -1.3765         1   
5                    0                 4  2.1564         1   
6                    1                 5  0.4284         1   
...                ...               ...     ...       ...   
1351927              1                 7  2.9355         1   
1351928              1                 9  3.8071         1   
1351930              1                 6  3.7813         1   
1351931              0                 6  2.9141         1   
1351932              0                 7  1.1437         1   

                                            RDKit_Molecule   
1        <rdkit.Chem.rdchem.Mol object at 0x000001D0CDC...  \
2        <rdkit.Chem.rdchem.Mol object at 0x000001D0C27...   
4        <rdkit.Chem.rdchem.Mol object at 0x000001D0CDC...   
5        <rdkit.Chem.rdchem.Mol object at 0x000001D0CDC...   
6        <rdkit.Chem.rdchem.Mol object at 0x000001D0CDD...   
...                                                    ...   
1351927                                                NaN   
1351928                                                NaN   
1351930                                                NaN   
1351931                                                NaN   
1351932                                                NaN   

                                                 Morgan2FP  
1        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
5        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
6        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
...                                                    ...  
1351927  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1351928  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1351930  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1351931  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1351932  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[1046938 rows x 8 columns]

In [3]:
with h5py.File('drugpredictor2/data/05_model_input/model_input.h5', 'w') as f:
    # Create a dataset with chunking enabled
    # Adjust chunks to be a manageable size for your memory
    f.create_dataset('my_data', data=pick, chunks=(1000, 100), compression='gzip')
print("Array saved to large_array.h5 with chunking.")

ValueError: Chunk shape must not be greater than data shape in any dimension. (1000, 100) is not compatible with (1324896, 8)

In [6]:
pick_val.columns

Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'RDKit_Molecule', 'Morgan2FP'],
      dtype='object')

In [7]:
pick.columns

NameError: name 'pick' is not defined

In [73]:
# Folder containing CSV files
folder_path = os.path.join('drugpredictor2', 'data','01_raw', 'csv')

# List to store DataFrames
dataframes = []

# Iterate over files in the folder
for file in os.listdir(folder_path):
    # Check if the file is a CSV
    if file.endswith('.csv'):
        file_path = os.path.join(folder_path, file)
        
        # Read CSV into DataFrame and append to list
        df = pd.read_csv(file_path)
        dataframes.append(df)

# Concatenate all DataFrames in the list
combined_df = pd.concat(dataframes, ignore_index=True)

# Save the combined DataFrame to a new CSV file
combined_df.to_csv(folder_path+'/combined_output.csv', index=False)

print("CSV files concatenated successfully.")

CSV files concatenated successfully.


In [105]:
""" ESTAMOS VALIDANDO ESTA"""
def train_test_split_column(model_input: pd.DataFrame, columns: dict, label: dict) -> tuple:
    """
    Function that makes a train/test split of a selected column of a pandas dataframe. Y values are taken from the label column.
    Args:
      input_pickle: input dataframe.
      column: name of the column selected as X values.
      label: name of the column selected as y values (target).
    Output: train/test tuple.
    """
    X = model_input[columns]
    y = model_input[label]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    return X_train, X_test, y_train, y_test

In [106]:
model_input = pd.read_pickle('drugpredictor2/data/05_model_input/input_table.pickle')
model_input

SMILES  Molecular Weight  H-Bond Donors   
0        CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C           203.238              0  \
1           CC(=O)OC(CC(=O)O)C[N+](C)(C)C           204.246              1   
2                    O=C(O)C1=CC=CC(O)C1O           156.137              3   
3                                 CC(O)CN            75.111              2   
4                      NCC(=O)COP(=O)(O)O           169.073              3   
5  O=[N+]([O-])c1ccc(Cl)c([N+](=O)[O-])c1           202.553              0   
6                      CCn1cnc2c(N)ncnc21           163.184              1   
7                     CCC(C)(O)C(O)C(=O)O           148.158              3   
8         O=P(O)(O)OC1C(O)C(O)C(O)C(O)C1O           260.135              7   

   H-Bond Acceptors    LogP  RuleFive   
0                 4 -1.2357         0  \
1                 3  0.0990         1   
2                 3 -0.7110         0   
3                 2 -0.6741         1   
4                 4 -1.3765         0   
5                 4  2.1564         0   
6                 5  0.4284         1   
7                 3 -0.4071         1   
8                 7 -3.7176         0   

                                      RDKit_Molecule   
0  <rdkit.Chem.rdchem.Mol object at 0x00000273395...  \
1  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
2  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
3  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
4  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
5  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
6  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
7  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
8  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   

                                           Morgan2FP  
0  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
5  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
6  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
7  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
8  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [107]:
label = 'RuleFive'
X_column = 'Morgan2FP'

In [ ]:
def reshape_input(tuple_split: tuple) -> tuple:
    """
    Function that reshapes the input data (X_train, X_test) to fit a 1D CNN model and determines both the number of classes /
        from the label data and the shape of the reshaped data.
    Input: train/test split tuple.
    Output: tuple with the data necessary to run the CNN model.
    """
    X_train, X_test, y_train, y_test = tuple_split
    print('X_train ', X_train, 'SHAPE: ', X_train.shape)
    print('X_test ', X_test)
    print('y_train ', y_train)
    # Transform arrays into lists
    X_train_array = np.array(list(X_train))
   
    X_test_array = np.array(list(X_test))
    
    # Determine number of classes
    #print(y_train)
    n_classes = len(np.unique(y_train))
    # Reshape
    reshaped_X_train= X_train_array.reshape((X_train_array.shape[0], X_train_array.shape[1], 1))
    reshaped_X_test= X_test_array.reshape((X_test_array.shape[0], X_test_array.shape[1], 1))
    # Determine in_shape
    in_shape = reshaped_X_train.shape[1:]
    #print(reshaped_X_train, reshaped_X_test, in_shape, n_classes)
    return reshaped_X_train, reshaped_X_test, in_shape, n_classes

In [133]:
def current_node(model_input: pd.DataFrame, x_column, label) -> tuple:
    splits = train_test_split_column(model_input, x_column, label)
    reshaped_X_train, reshaped_X_test, in_shape, n_classes = reshape_input(splits)
    print(reshaped_X_train, reshaped_X_train.shape)
    print(reshaped_X_test)
    print(in_shape)
    print(n_classes)

In [134]:
current_node(model_input,X_column,label)

X_train  0    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
8    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
6    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: Morgan2FP, dtype: object SHAPE:  (6,)
X_test  7    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: Morgan2FP, dtype: object
y_train  0    0
8    0
2    0
4    0
3    1
6    1
Name: RuleFive, dtype: int64
[[[0]
  [1]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [1]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]] (6, 2048, 1)
[[[0]
  [1]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [1]


In [25]:
def fizzBuzz(n):
    for x in range(1,n+1):
        if x%3 == 0 and x % 5 == 0:
            print('FizzBuzz2')
        elif x%3 == 0:
            print('Fizz')
        elif x%5 == 0:
            print('Buzz')
        else:
            print(x)

In [26]:
fizzBuzz(15
         )

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz2


In [ ]:
range(0,15)

In [31]:
mylist = ['.' for n in range(1,12)]

In [33]:
mylist

['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.']

In [40]:
word = 'muggle'

In [41]:
mylist= [l for l in word]

In [42]:
mylist

['m', 'u', 'g', 'g', 'l', 'e']

In [43]:
12 - len(mylist)

6

In [47]:
5%2

1

In [46]:
mylist

['m', 'u', 'g', 'g', 'l', 'e', '...']

In [38]:
mystring = ''.join(mylist)
mystring

'.....g.....'

In [28]:
mystring

'...............'

In [29]:
mystring[5] = 'h'

TypeError: 'str' object does not support item assignment

In [65]:
def centerDisplay(width, content):
    for word in content:
        total_periods = width-len(word)
        half_periods = total_periods/2
        rest_periods = total_periods%2
        final_string = ('.'*int(half_periods))+('.'*int(rest_periods))+word+('.'*int(half_periods))
        return final_string

In [66]:
centerDisplay(11, ["Middle"])

'...Middle..'

In [67]:
def shopping_total(n, items):
    total =0
    for item in items:
        if item[1] < 50:
            total += item[1]
        else:
            total += 9/10*item[1]
    return total

In [75]:
def shopping_total(n, items):
    result = lambda n, items: sum(price if price < 50 else 0.9 * price for _, price in items)
    return result

In [76]:
shopping_total(6,
[
('Kiwi',15),
('Strawberry',22),
('Avacado',60),
('Guava',35),
('Pineapple',70),
('Pumpkin',45)])

<function __main__.shopping_total.<locals>.<lambda>(n, items)>

In [ ]:
prices_list = [9/10*item[1] for item in items if item[1]<50 else item[1]]