In [7]:
import h5py
import kedro_datasets
from kedro.io import data_catalog
import pandas as pd
import os
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
dir(kedro_datasets)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__']

In [ ]:
data_catalog.

TypeError: 'module' object is not iterable

In [7]:
model_input = pd.read_csv('../data/05_model_input/model_input.csv')
model_input_val = pd.read_csv('../data/05_model_input/model_input_val.csv')
combined_df_w_fp = pd.concat([model_input, model_input_val], ignore_index=True)

In [8]:
model_input.tail()

SMILES  Molecular Weight   
1324891   CC(=O)COc1c(C(=O)Nc2ccc(C)cc2)nnn1-c1ccc(C)cc1           364.405  \
1324892  O=C(COc1c(C(=O)Nc2ccccc2)nnn1-c1ccccc1)c1ccccc1           398.422   
1324893         C(=Nc1nnc(N2CCC(c3ccccc3)CC2)s1)N1CCOCC1           357.483   
1324894     C[C@@H]1CN(c2nnc(N=CN3CCOCC3)s2)C[C@@H](C)O1           311.411   
1324895       Clc1cccc(N2CCN(c3nnc(N=CN4CCCCC4)s3)CC2)c1           390.944   

         H-Bond Donors  H-Bond Acceptors     LogP          Morgan2FP  RuleFive  
1324891              1                 6  3.10424  [0 0 0 ... 0 0 0]         1  
1324892              1                 6  3.78130  [0 0 0 ... 0 0 0]         1  
1324893              0                 6  2.91410  [0 0 0 ... 0 0 0]         1  
1324894              0                 7  1.14370  [0 0 0 ... 0 0 0]         1  
1324895              0                 6  3.66380  [0 0 1 ... 0 0 0]         1

In [13]:
combined_df_w_fp.to_csv('../data/05_model_input/presplit_model_input.csv', index=False)

In [14]:
len(combined_df_w_fp)

1351934

In [2]:
pick = pd.read_pickle('drugpredictor2/data/05_model_input/input_table.pickle')

In [4]:
pick_val = pd.read_pickle('drugpredictor2/data/05_model_input/input_table_val.pickle')

In [11]:
val_dataset_mock = pd.read_pickle('drugpredictor2/data/05_model_input/input_table_val_mock.pickle')

In [4]:
mock_dataset = pd.read_pickle('../data/05_model_input/input_table_mock.pickle')

In [5]:
mock_dataset

SMILES  Molecular Weight   
1                            CC(=O)OC(CC(=O)O)C[N+](C)(C)C           204.246  \
2                                     O=C(O)C1=CC=CC(O)C1O           156.137   
4                                       NCC(=O)COP(=O)(O)O           169.073   
5                   O=[N+]([O-])c1ccc(Cl)c([N+](=O)[O-])c1           202.553   
6                                       CCn1cnc2c(N)ncnc21           163.184   
...                                                    ...               ...   
1351927        CCOc1c(C(=O)Nc2ccc(OC)cc2)nnn1-c1ccc(OC)cc1           368.393   
1351928  COc1ccc(NC(=O)c2nnn(-c3ccc(OC)cc3)c2OCC(=O)c2c...           488.500   
1351930    O=C(COc1c(C(=O)Nc2ccccc2)nnn1-c1ccccc1)c1ccccc1           398.422   
1351931           C(=Nc1nnc(N2CCC(c3ccccc3)CC2)s1)N1CCOCC1           357.483   
1351932       C[C@@H]1CN(c2nnc(N=CN3CCOCC3)s2)C[C@@H](C)O1           311.411   

         H-Bond Donors  H-Bond Acceptors    LogP  RuleFive   
1                    1                 3  0.0990         1  \
2                    3                 3 -0.7110         1   
4                    3                 4 -1.3765         1   
5                    0                 4  2.1564         1   
6                    1                 5  0.4284         1   
...                ...               ...     ...       ...   
1351927              1                 7  2.9355         1   
1351928              1                 9  3.8071         1   
1351930              1                 6  3.7813         1   
1351931              0                 6  2.9141         1   
1351932              0                 7  1.1437         1   

                                            RDKit_Molecule   
1        <rdkit.Chem.rdchem.Mol object at 0x000001D0CDC...  \
2        <rdkit.Chem.rdchem.Mol object at 0x000001D0C27...   
4        <rdkit.Chem.rdchem.Mol object at 0x000001D0CDC...   
5        <rdkit.Chem.rdchem.Mol object at 0x000001D0CDC...   
6        <rdkit.Chem.rdchem.Mol object at 0x000001D0CDD...   
...                                                    ...   
1351927                                                NaN   
1351928                                                NaN   
1351930                                                NaN   
1351931                                                NaN   
1351932                                                NaN   

                                                 Morgan2FP  
1        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
5        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
6        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
...                                                    ...  
1351927  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1351928  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1351930  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1351931  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1351932  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[1046938 rows x 8 columns]

In [3]:
with h5py.File('drugpredictor2/data/05_model_input/model_input.h5', 'w') as f:
    # Create a dataset with chunking enabled
    # Adjust chunks to be a manageable size for your memory
    f.create_dataset('my_data', data=pick, chunks=(1000, 100), compression='gzip')
print("Array saved to large_array.h5 with chunking.")

ValueError: Chunk shape must not be greater than data shape in any dimension. (1000, 100) is not compatible with (1324896, 8)

In [6]:
pick_val.columns

Index(['SMILES', 'Molecular Weight', 'H-Bond Donors', 'H-Bond Acceptors',
       'LogP', 'RuleFive', 'RDKit_Molecule', 'Morgan2FP'],
      dtype='object')

In [7]:
pick.columns

NameError: name 'pick' is not defined

In [73]:
# Folder containing CSV files
folder_path = os.path.join('drugpredictor2', 'data','01_raw', 'csv')

# List to store DataFrames
dataframes = []

# Iterate over files in the folder
for file in os.listdir(folder_path):
    # Check if the file is a CSV
    if file.endswith('.csv'):
        file_path = os.path.join(folder_path, file)
        
        # Read CSV into DataFrame and append to list
        df = pd.read_csv(file_path)
        dataframes.append(df)

# Concatenate all DataFrames in the list
combined_df = pd.concat(dataframes, ignore_index=True)

# Save the combined DataFrame to a new CSV file
combined_df.to_csv(folder_path+'/combined_output.csv', index=False)

print("CSV files concatenated successfully.")

CSV files concatenated successfully.


In [105]:
""" ESTAMOS VALIDANDO ESTA"""
def train_test_split_column(model_input: pd.DataFrame, columns: dict, label: dict) -> tuple:
    """
    Function that makes a train/test split of a selected column of a pandas dataframe. Y values are taken from the label column.
    Args:
      input_pickle: input dataframe.
      column: name of the column selected as X values.
      label: name of the column selected as y values (target).
    Output: train/test tuple.
    """
    X = model_input[columns]
    y = model_input[label]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    return X_train, X_test, y_train, y_test

In [106]:
model_input = pd.read_pickle('drugpredictor2/data/05_model_input/input_table.pickle')
model_input

SMILES  Molecular Weight  H-Bond Donors   
0        CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C           203.238              0  \
1           CC(=O)OC(CC(=O)O)C[N+](C)(C)C           204.246              1   
2                    O=C(O)C1=CC=CC(O)C1O           156.137              3   
3                                 CC(O)CN            75.111              2   
4                      NCC(=O)COP(=O)(O)O           169.073              3   
5  O=[N+]([O-])c1ccc(Cl)c([N+](=O)[O-])c1           202.553              0   
6                      CCn1cnc2c(N)ncnc21           163.184              1   
7                     CCC(C)(O)C(O)C(=O)O           148.158              3   
8         O=P(O)(O)OC1C(O)C(O)C(O)C(O)C1O           260.135              7   

   H-Bond Acceptors    LogP  RuleFive   
0                 4 -1.2357         0  \
1                 3  0.0990         1   
2                 3 -0.7110         0   
3                 2 -0.6741         1   
4                 4 -1.3765         0   
5                 4  2.1564         0   
6                 5  0.4284         1   
7                 3 -0.4071         1   
8                 7 -3.7176         0   

                                      RDKit_Molecule   
0  <rdkit.Chem.rdchem.Mol object at 0x00000273395...  \
1  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
2  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
3  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
4  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
5  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
6  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
7  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   
8  <rdkit.Chem.rdchem.Mol object at 0x00000273395...   

                                           Morgan2FP  
0  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
5  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
6  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
7  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
8  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [107]:
label = 'RuleFive'
X_column = 'Morgan2FP'

In [130]:
def reshape_input(tuple_split: tuple) -> tuple:
    """
    Function that reshapes the input data (X_train, X_test) to fit a 1D CNN model and determines both the number of classes \
        from the label data and the shape of the reshaped data.
    Input: train/test split tuple.
    Output: tuple with the data necessary to run the CNN model.
    """
    X_train, X_test, y_train, y_test = tuple_split
    print('X_train ', X_train, 'SHAPE: ', X_train.shape)
    print('X_test ', X_test)
    print('y_train ', y_train)
    # Transform arrays into lists
    X_train_array = np.array(list(X_train))
   
    X_test_array = np.array(list(X_test))
    
    # Determine number of classes
    #print(y_train)
    n_classes = len(np.unique(y_train))
    # Reshape
    reshaped_X_train= X_train_array.reshape((X_train_array.shape[0], X_train_array.shape[1], 1))
    reshaped_X_test= X_test_array.reshape((X_test_array.shape[0], X_test_array.shape[1], 1))
    # Determine in_shape
    in_shape = reshaped_X_train.shape[1:]
    #print(reshaped_X_train, reshaped_X_test, in_shape, n_classes)
    return reshaped_X_train, reshaped_X_test, in_shape, n_classes

In [133]:
def current_node(model_input: pd.DataFrame, x_column, label) -> tuple:
    splits = train_test_split_column(model_input, x_column, label)
    reshaped_X_train, reshaped_X_test, in_shape, n_classes = reshape_input(splits)
    print(reshaped_X_train, reshaped_X_train.shape)
    print(reshaped_X_test)
    print(in_shape)
    print(n_classes)

In [134]:
current_node(model_input,X_column,label)

X_train  0    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
8    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
6    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: Morgan2FP, dtype: object SHAPE:  (6,)
X_test  7    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: Morgan2FP, dtype: object
y_train  0    0
8    0
2    0
4    0
3    1
6    1
Name: RuleFive, dtype: int64
[[[0]
  [1]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [1]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]] (6, 2048, 1)
[[[0]
  [1]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [1]
